// Code generated by go-bindata.
// sources:
// static/index.html
// static/templates/index.html
// static/vendor/css/bootstrap-theme.css
// static/vendor/css/bootstrap-theme.css.map
// static/vendor/css/bootstrap-theme.min.css
// static/vendor/css/bootstrap-theme.min.css.map
// static/vendor/css/bootstrap.css
// static/vendor/css/bootstrap.css.map
// static/vendor/css/bootstrap.min.css
// static/vendor/css/bootstrap.min.css.map
// static/vendor/fonts/glyphicons-halflings-regular.eot
// static/vendor/fonts/glyphicons-halflings-regular.svg
// static/vendor/fonts/glyphicons-halflings-regular.ttf
// static/vendor/fonts/glyphicons-halflings-regular.woff
// static/vendor/fonts/glyphicons-halflings-regular.woff2
// static/vendor/js/bootstrap.js
// static/vendor/js/bootstrap.min.js
// static/vendor/js/jquery.min.js
// DO NOT EDIT!

package server

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// indexHtml reads file data from disk. It returns an error on failure.
func indexHtml() (*asset, error) {
	path := "/Users/vovka/workspace/pet_projects/Trinity/src/github.com/k4jt/trinity/static/index.html"
	name := "index.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// templatesIndexHtml reads file data from disk. It returns an error on failure.
func templatesIndexHtml() (*asset, error) {
	path := "/Users/vovka/workspace/pet_projects/Trinity/src/github.com/k4jt/trinity/static/templates/index.html"
	name := "templates/index.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// vendorCssBootstrapThemeCss reads file data from disk. It returns an error on failure.
func vendorCssBootstrapThemeCss() (*asset, error) {
	path := "/Users/vovka/workspace/pet_projects/Trinity/src/github.com/k4jt/trinity/static/vendor/css/bootstrap-theme.css"
	name := "vendor/css/bootstrap-theme.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// vendorCssBootstrapThemeCssMap reads file data from disk. It returns an error on failure.
func vendorCssBootstrapThemeCssMap() (*asset, error) {
	path := "/Users/vovka/workspace/pet_projects/Trinity/src/github.com/k4jt/trinity/static/vendor/css/bootstrap-theme.css.map"
	name := "vendor/css/bootstrap-theme.css.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// vendorCssBootstrapThemeMinCss reads file data from disk. It returns an error on failure.
func vendorCssBootstrapThemeMinCss() (*asset, error) {
	path := "/Users/vovka/workspace/pet_projects/Trinity/src/github.com/k4jt/trinity/static/vendor/css/bootstrap-theme.min.css"
	name := "vendor/css/bootstrap-theme.min.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// vendorCssBootstrapThemeMinCssMap reads file data from disk. It returns an error on failure.
func vendorCssBootstrapThemeMinCssMap() (*asset, error) {
	path := "/Users/vovka/workspace/pet_projects/Trinity/src/github.com/k4jt/trinity/static/vendor/css/bootstrap-theme.min.css.map"
	name := "vendor/css/bootstrap-theme.min.css.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// vendorCssBootstrapCss reads file data from disk. It returns an error on failure.
func vendorCssBootstrapCss() (*asset, error) {
	path := "/Users/vovka/workspace/pet_projects/Trinity/src/github.com/k4jt/trinity/static/vendor/css/bootstrap.css"
	name := "vendor/css/bootstrap.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// vendorCssBootstrapCssMap reads file data from disk. It returns an error on failure.
func vendorCssBootstrapCssMap() (*asset, error) {
	path := "/Users/vovka/workspace/pet_projects/Trinity/src/github.com/k4jt/trinity/static/vendor/css/bootstrap.css.map"
	name := "vendor/css/bootstrap.css.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// vendorCssBootstrapMinCss reads file data from disk. It returns an error on failure.
func vendorCssBootstrapMinCss() (*asset, error) {
	path := "/Users/vovka/workspace/pet_projects/Trinity/src/github.com/k4jt/trinity/static/vendor/css/bootstrap.min.css"
	name := "vendor/css/bootstrap.min.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// vendorCssBootstrapMinCssMap reads file data from disk. It returns an error on failure.
func vendorCssBootstrapMinCssMap() (*asset, error) {
	path := "/Users/vovka/workspace/pet_projects/Trinity/src/github.com/k4jt/trinity/static/vendor/css/bootstrap.min.css.map"
	name := "vendor/css/bootstrap.min.css.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// vendorFontsGlyphiconsHalflingsRegularEot reads file data from disk. It returns an error on failure.
func vendorFontsGlyphiconsHalflingsRegularEot() (*asset, error) {
	path := "/Users/vovka/workspace/pet_projects/Trinity/src/github.com/k4jt/trinity/static/vendor/fonts/glyphicons-halflings-regular.eot"
	name := "vendor/fonts/glyphicons-halflings-regular.eot"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// vendorFontsGlyphiconsHalflingsRegularSvg reads file data from disk. It returns an error on failure.
func vendorFontsGlyphiconsHalflingsRegularSvg() (*asset, error) {
	path := "/Users/vovka/workspace/pet_projects/Trinity/src/github.com/k4jt/trinity/static/vendor/fonts/glyphicons-halflings-regular.svg"
	name := "vendor/fonts/glyphicons-halflings-regular.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// vendorFontsGlyphiconsHalflingsRegularTtf reads file data from disk. It returns an error on failure.
func vendorFontsGlyphiconsHalflingsRegularTtf() (*asset, error) {
	path := "/Users/vovka/workspace/pet_projects/Trinity/src/github.com/k4jt/trinity/static/vendor/fonts/glyphicons-halflings-regular.ttf"
	name := "vendor/fonts/glyphicons-halflings-regular.ttf"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// vendorFontsGlyphiconsHalflingsRegularWoff reads file data from disk. It returns an error on failure.
func vendorFontsGlyphiconsHalflingsRegularWoff() (*asset, error) {
	path := "/Users/vovka/workspace/pet_projects/Trinity/src/github.com/k4jt/trinity/static/vendor/fonts/glyphicons-halflings-regular.woff"
	name := "vendor/fonts/glyphicons-halflings-regular.woff"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// vendorFontsGlyphiconsHalflingsRegularWoff2 reads file data from disk. It returns an error on failure.
func vendorFontsGlyphiconsHalflingsRegularWoff2() (*asset, error) {
	path := "/Users/vovka/workspace/pet_projects/Trinity/src/github.com/k4jt/trinity/static/vendor/fonts/glyphicons-halflings-regular.woff2"
	name := "vendor/fonts/glyphicons-halflings-regular.woff2"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// vendorJsBootstrapJs reads file data from disk. It returns an error on failure.
func vendorJsBootstrapJs() (*asset, error) {
	path := "/Users/vovka/workspace/pet_projects/Trinity/src/github.com/k4jt/trinity/static/vendor/js/bootstrap.js"
	name := "vendor/js/bootstrap.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// vendorJsBootstrapMinJs reads file data from disk. It returns an error on failure.
func vendorJsBootstrapMinJs() (*asset, error) {
	path := "/Users/vovka/workspace/pet_projects/Trinity/src/github.com/k4jt/trinity/static/vendor/js/bootstrap.min.js"
	name := "vendor/js/bootstrap.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// vendorJsJqueryMinJs reads file data from disk. It returns an error on failure.
func vendorJsJqueryMinJs() (*asset, error) {
	path := "/Users/vovka/workspace/pet_projects/Trinity/src/github.com/k4jt/trinity/static/vendor/js/jquery.min.js"
	name := "vendor/js/jquery.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"index.html":                                      indexHtml,
	"templates/index.html":                            templatesIndexHtml,
	"vendor/css/bootstrap-theme.css":                  vendorCssBootstrapThemeCss,
	"vendor/css/bootstrap-theme.css.map":              vendorCssBootstrapThemeCssMap,
	"vendor/css/bootstrap-theme.min.css":              vendorCssBootstrapThemeMinCss,
	"vendor/css/bootstrap-theme.min.css.map":          vendorCssBootstrapThemeMinCssMap,
	"vendor/css/bootstrap.css":                        vendorCssBootstrapCss,
	"vendor/css/bootstrap.css.map":                    vendorCssBootstrapCssMap,
	"vendor/css/bootstrap.min.css":                    vendorCssBootstrapMinCss,
	"vendor/css/bootstrap.min.css.map":                vendorCssBootstrapMinCssMap,
	"vendor/fonts/glyphicons-halflings-regular.eot":   vendorFontsGlyphiconsHalflingsRegularEot,
	"vendor/fonts/glyphicons-halflings-regular.svg":   vendorFontsGlyphiconsHalflingsRegularSvg,
	"vendor/fonts/glyphicons-halflings-regular.ttf":   vendorFontsGlyphiconsHalflingsRegularTtf,
	"vendor/fonts/glyphicons-halflings-regular.woff":  vendorFontsGlyphiconsHalflingsRegularWoff,
	"vendor/fonts/glyphicons-halflings-regular.woff2": vendorFontsGlyphiconsHalflingsRegularWoff2,
	"vendor/js/bootstrap.js":                          vendorJsBootstrapJs,
	"vendor/js/bootstrap.min.js":                      vendorJsBootstrapMinJs,
	"vendor/js/jquery.min.js":                         vendorJsJqueryMinJs,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"index.html": &bintree{indexHtml, map[string]*bintree{}},
	"templates": &bintree{nil, map[string]*bintree{
		"index.html": &bintree{templatesIndexHtml, map[string]*bintree{}},
	}},
	"vendor": &bintree{nil, map[string]*bintree{
		"css": &bintree{nil, map[string]*bintree{
			"bootstrap-theme.css":         &bintree{vendorCssBootstrapThemeCss, map[string]*bintree{}},
			"bootstrap-theme.css.map":     &bintree{vendorCssBootstrapThemeCssMap, map[string]*bintree{}},
			"bootstrap-theme.min.css":     &bintree{vendorCssBootstrapThemeMinCss, map[string]*bintree{}},
			"bootstrap-theme.min.css.map": &bintree{vendorCssBootstrapThemeMinCssMap, map[string]*bintree{}},
			"bootstrap.css":               &bintree{vendorCssBootstrapCss, map[string]*bintree{}},
			"bootstrap.css.map":           &bintree{vendorCssBootstrapCssMap, map[string]*bintree{}},
			"bootstrap.min.css":           &bintree{vendorCssBootstrapMinCss, map[string]*bintree{}},
			"bootstrap.min.css.map":       &bintree{vendorCssBootstrapMinCssMap, map[string]*bintree{}},
		}},
		"fonts": &bintree{nil, map[string]*bintree{
			"glyphicons-halflings-regular.eot":   &bintree{vendorFontsGlyphiconsHalflingsRegularEot, map[string]*bintree{}},
			"glyphicons-halflings-regular.svg":   &bintree{vendorFontsGlyphiconsHalflingsRegularSvg, map[string]*bintree{}},
			"glyphicons-halflings-regular.ttf":   &bintree{vendorFontsGlyphiconsHalflingsRegularTtf, map[string]*bintree{}},
			"glyphicons-halflings-regular.woff":  &bintree{vendorFontsGlyphiconsHalflingsRegularWoff, map[string]*bintree{}},
			"glyphicons-halflings-regular.woff2": &bintree{vendorFontsGlyphiconsHalflingsRegularWoff2, map[string]*bintree{}},
		}},
		"js": &bintree{nil, map[string]*bintree{
			"bootstrap.js":     &bintree{vendorJsBootstrapJs, map[string]*bintree{}},
			"bootstrap.min.js": &bintree{vendorJsBootstrapMinJs, map[string]*bintree{}},
			"jquery.min.js":    &bintree{vendorJsJqueryMinJs, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
